### PR TITLE
Switch for LPT order

### PR DESCRIPTION
**Pull request by marcelo-alvarez**
Adds a switch for LPT order: 
- n=0; s1=s2=None
- n=1; s2=None
- n=2; full LPT

@1cosmologist can you have a quick look before I merge? Thanks.

### CODE REVIEW

**Review by 1cosmologist — APPROVED** [review]
Looks good to me.

**Comment by 1cosmologist** [comment]
> Adds a switch for LPT order:
> 
> * n=0; s1=s2=None
> * n=1; s2=None
> * n=2; full LPT

@marcelo-alvarez  I did not see a `n=0` switch. Seems like n=1 is the default. Can you confirm?

**Review by 1cosmologist — APPROVED** [review]
This is fine, but I would like to open an issue on xgfield that nlpt=0 is not supported.

**Comment by marcelo-alvarez** [comment]
Should be solved now, thanks for catching these.

**Comment by 1cosmologist** [comment]
Added an issue to xgfield (https://github.com/exgalsky/xgfield/issues/10) to add support for `nlpt=0` and additionally catch exceptions for illegal nlpt values.

**Pull request merged**
